              hhonso hiopwj \u0111u\u01B0\u1EE3c to=\u1EA1o yhanhf rttuf hai d h\u01B0wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.11/apache-maven-3.9.11-bin.zip
