# \uD83C\uDF10 Server port
server.port=${PORT:8080}

# \uD83C\uDF0D Spring Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.application.name=KimThanhPhatMVC

# \uD83E\uDDE9 Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# \u2601\uFE0F Cloudinary (d\u00F9ng ENV khi deploy)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Show SQL
spring.jpa.show-sql=true
