# === LOCAL DATABASE (MySQL) ===
spring.datasource.url=jdbc:mysql://localhost:3306/kimthanhphatdb
spring.datasource.username=root
spring.datasource.password=211298
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Cloudinary local (d\u00F9ng key th\u1EADt)
cloudinary.cloud_name=drhxxliht
cloudinary.api_key=644869335759945
cloudinary.api_secret=QbELHnJyKSDzEd_qRKPD5hXl_DU
